CREATE DATABASE IF NOT EXISTS db_main;

USE db_main;

CREATE TABLE IF NOT EXISTS SITES (
    SITES_ID      INT NOT NULL AUTO_INCREMENT,
    STACK_NAME    VARCHAR(255)        NOT NULL,  
    FILE_URL     VARCHAR(255)         NULL,
    SITE_CONTENT VARCHAR(255)         NULL,
    PROJECT_NAME VARCHAR(255)         NOT NULL,
    DATE_CREATED VARCHAR(50)          NOT NULL,
    PRIMARY KEY(SITES_ID)
);

CREATE TABLE IF NOT EXISTS VM (
    VM_ID      INT NOT NULL AUTO_INCREMENT,
    STACK_NAME    VARCHAR(255)        NOT NULL,  
    PROJECT_NAME VARCHAR(255)         NOT NULL,
    INSTANCE_TYPE VARCHAR(255)        NOT NULL,
    KEYDATA VARCHAR(255)             NOT NULL,
    DATE_CREATED VARCHAR(50)          NOT NULL,
    PRIMARY KEY(VM_ID)
);

